### ISSUE TITLE
Error: Request Notify{model: ArrayObject} is not supported

### ISSUE THREAD

**Issue by orzeszki** [SoftifyDev/SyliusImojePlugin#2]
Dzień dobry,
po ustawieniu adresu notyfikacji ```https://mojestrona.pl/payment/notify/unsafe/imoje``` na stronie bramki zwraca mi taki błąd:

```Error: Request Notify{model: ArrayObject} is not supported. Make sure the gateway supports the requests and there is an action which supports this request (The method returns true). There may be a bug, so look for a related issue on the issue tracker. www/vendor/payum/payum/src/Payum/Core/Exception/RequestNotSupportedException.php:57```

W sylius_shop.yaml mam taką kolejność:
```
imoje_plugin_shop:
    resource: "@SoftifySyliusImojePlugin/Resources/config/shop_routing.yml"

sylius_shop_payum:
    resource: "@SyliusShopBundle/Resources/config/routing/payum.yml"
    
payum_notify_do:
    path: /{_locale}/payment/notify/{payum_token}
    methods: [POST,GET]
    controller: Payum\Bundle\PayumBundle\Controller\NotifyController::doAction
```

Musiała taka być, bo inaczej nie plugin nie mógł nadpisać standardowego zachowania dla ```payum_notify_do```.

Co może tutaj być nie tak? Bramka normalnie potrafi przekazać dane o płatności w momencie kiedy kliknie się "Wróć do sklepu", ale poprzez notyfikację to nie działa.
